In [25]:
import numpy as np
import os

In [3]:
E = np.ones((2,3))
print(E)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
print(E*42)

[[42. 42. 42.]
 [42. 42. 42.]]


In [5]:
F = np.linspace(0,10,14)
print(F)

[ 0.          0.76923077  1.53846154  2.30769231  3.07692308  3.84615385
  4.61538462  5.38461538  6.15384615  6.92307692  7.69230769  8.46153846
  9.23076923 10.        ]


In [6]:
newarray = np.loadtxt('../Datasets/RecentEarthquakes/earthquakeLocations.txt')
print(newarray)

[[  66.07 -149.03]
 [  38.83 -122.8 ]
 [  32.92 -115.47]
 [  47.63 -122.51]
 [  60.97 -151.24]
 [  37.65 -118.85]
 [  53.2  -161.3 ]
 [  19.41 -155.28]
 [  38.84 -122.83]
 [  36.88  -89.12]]


In [7]:
np.array([[1, 2, 3], [4, 2, 0], ['Xiao Long', 'Jill', 'Jose']], dtype = 'object')

array([[1, 2, 3],
       [4, 2, 0],
       ['Xiao Long', 'Jill', 'Jose']], dtype=object)

In [8]:
G = np.ndarray(shape=(2,2), dtype=(float))
print(G)

[[-1.49166815e-154 -1.29073897e-231]
 [ 6.93440171e-310  3.47478249e-309]]


In [10]:
A = np.array([[1, 2, 3], [4, 2, 0], [1, 1, 2]])
print("The dimensions of A are: ", A.ndim)
A.shape

The dimensions of A are:  2


(3, 3)

In [11]:
B_real = np.arange(0, 10, 0.2) 
# We can take a 1-D array with 50 elements and reshape it into, say a 5 X 10 2-D array:
B_real_2D = B_real.reshape((5, 10))
print('B_real:\n', B_real)
print("\n")
print('B_real after reshaping:\n', B_real_2D)

B_real:
 [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


B_real after reshaping:
 [[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]]


In [13]:
B_real_1D = B_real_2D.flatten()
print(B_real_1D)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [16]:
print(B_real_2D)
print(B_real_2D.transpose())

[[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]]
[[0.  2.  4.  6.  8. ]
 [0.2 2.2 4.2 6.2 8.2]
 [0.4 2.4 4.4 6.4 8.4]
 [0.6 2.6 4.6 6.6 8.6]
 [0.8 2.8 4.8 6.8 8.8]
 [1.  3.  5.  7.  9. ]
 [1.2 3.2 5.2 7.2 9.2]
 [1.4 3.4 5.4 7.4 9.4]
 [1.6 3.6 5.6 7.6 9.6]
 [1.8 3.8 5.8 7.8 9.8]]


In [18]:
B = A[0:2]
print(B)

[[1 2 3]
 [4 2 0]]


In [19]:
time = np.linspace(0, 10, 11)
lateTime = time[time  > 5.0]
print(lateTime)

[ 6.  7.  8.  9. 10.]


In [23]:
distance = time / 3.0
print(distance)
lateDistance = distance[time > 5.0]
print(lateDistance)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333]
[2.         2.33333333 2.66666667 3.         3.33333333]


In [24]:
boolTime = time > 5.0
print(boolTime)

[False False False False False False  True  True  True  True  True]


In [26]:
np.savetxt('A.txt', A)

In [27]:
os.remove('A.txt')